## MSSQL Connection String 
## Server=localhost,1433;Initial Catalog=MyDb;Integrated Security=True;User Id=sa;Password=ChangeMe!123;

version: '3.1'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql01
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: $MSSQL_ACCEPT_EULA
      MSSQL_SA_PASSWORD: $MSSQL_SA_PASSWORD
      MSSQL_PID: $MSSQL_PID
      TZ: $MSSQL_TIME_ZONE
    volumes:
      - mssqldb01:/var/opt/mssql:rw

volumes:
    mssqldb01: